// ============================================================
// Verdict — Mock Data Layer
// ============================================================

export interface User {
  id: string;
  username: string;
  avatar: string;
  aura: number;
  wins: number;
  losses: number;
  winRate: number;
  rank: string;
  rankColor: string;
  streak: number;
  coins: number;
  badges: string[];
  joinDate: string;
}

export interface BattleCase {
  id: string;
  sideA: string;
  sideB: string;
  category: string;
  difficulty: "Bronze" | "Silver" | "Gold" | "Platinum";
  difficultyColor: string;
  teamA: (User | null)[];
  teamB: (User | null)[];
  spectators: User[];
  maxSpectators: number;
  status: "waiting" | "live" | "verdict" | "finished";
  timer: number;
  totalTimer: number;
  chatMessages: ChatMessage[];
  aiVerdict: AiVerdict | null;
  auraStake: number;
  viewers: number;
}

export interface ChatMessage {
  id: string;
  userId: string;
  username: string;
  text: string;
  timestamp: number;
  isAi: boolean;
  type: "argument" | "ai_kick" | "ai_warning" | "spectator_reaction" | "system";
  reaction?: string;
}

export interface AiVerdict {
  winner: "A" | "B";
  scoreA: number;
  scoreB: number;
  bestArgument: { userId: string; username: string; text: string };
  mostRoasted: { userId: string; username: string; roastCount: number };
  summary: string;
  coinsAwarded: number;
  auraChange: { gained: number; lost: number };
}

export interface Category {
  id: string;
  name: string;
  icon: string;
  battleCount: number;
  color: string;
}

export interface Quest {
  id: string;
  title: string;
  description: string;
  progress: number;
  target: number;
  reward: { coins: number; aura: number };
  completed: boolean;
}

export interface MarketplaceItem {
  id: string;
  name: string;
  type: "frame" | "title" | "badge" | "effect";
  cost: number;
  rarity: "common" | "rare" | "epic" | "legendary";
  rarityColor: string;
  owned: boolean;
  equipped: boolean;
}

export interface GroupInfo {
  id: string;
  name: string;
  members: number;
  description: string;
  category: string;
  isJoined: boolean;
}

// ============================================================
// Mock Users
// ============================================================

export const mockCurrentUser: User = {
  id: "u-me",
  username: "You",
  avatar: "YO",
  aura: 1250,
  wins: 18,
  losses: 12,
  winRate: 60,
  rank: "Lawyer",
  rankColor: "text-orange-600",
  streak: 3,
  coins: 850,
  badges: ["Hot Streak", "Case Master"],
  joinDate: "2025-01-15",
};

export const mockUsers: User[] = [
  {
    id: "u-1",
    username: "DK",
    avatar: "DK",
    aura: 5200,
    wins: 94,
    losses: 21,
    winRate: 82,
    rank: "Legend",
    rankColor: "text-orange-600",
    streak: 12,
    coins: 12400,
    badges: ["Top 10", "Hot Streak", "Case Master", "Unstoppable"],
    joinDate: "2024-06-10",
  },
  {
    id: "u-2",
    username: "AR",
    avatar: "AR",
    aura: 3850,
    wins: 67,
    losses: 28,
    winRate: 71,
    rank: "Supreme Court",
    rankColor: "text-[#4D7C0F]",
    streak: 5,
    coins: 8200,
    badges: ["Top 10", "Case Master"],
    joinDate: "2024-08-22",
  },
  {
    id: "u-3",
    username: "PS",
    avatar: "PS",
    aura: 2940,
    wins: 52,
    losses: 30,
    winRate: 63,
    rank: "Judge",
    rankColor: "text-stone-700",
    streak: 2,
    coins: 5600,
    badges: ["Case Master"],
    joinDate: "2024-09-05",
  },
  {
    id: "u-4",
    username: "VK",
    avatar: "VK",
    aura: 2100,
    wins: 41,
    losses: 22,
    winRate: 65,
    rank: "Judge",
    rankColor: "text-stone-700",
    streak: 4,
    coins: 4300,
    badges: ["Hot Streak"],
    joinDate: "2024-10-12",
  },
  {
    id: "u-5",
    username: "RM",
    avatar: "RM",
    aura: 1750,
    wins: 35,
    losses: 20,
    winRate: 64,
    rank: "Lawyer",
    rankColor: "text-orange-600",
    streak: 1,
    coins: 3200,
    badges: [],
    joinDate: "2024-11-01",
  },
  {
    id: "u-6",
    username: "NK",
    avatar: "NK",
    aura: 1320,
    wins: 28,
    losses: 18,
    winRate: 61,
    rank: "Lawyer",
    rankColor: "text-orange-600",
    streak: 3,
    coins: 2100,
    badges: ["Case Master"],
    joinDate: "2024-11-20",
  },
  {
    id: "u-7",
    username: "SP",
    avatar: "SP",
    aura: 980,
    wins: 19,
    losses: 16,
    winRate: 54,
    rank: "Lawyer",
    rankColor: "text-orange-600",
    streak: 0,
    coins: 1400,
    badges: [],
    joinDate: "2024-12-05",
  },
  {
    id: "u-8",
    username: "AJ",
    avatar: "AJ",
    aura: 640,
    wins: 12,
    losses: 14,
    winRate: 46,
    rank: "Citizen",
    rankColor: "text-stone-500",
    streak: 1,
    coins: 800,
    badges: [],
    joinDate: "2025-01-08",
  },
  {
    id: "u-9",
    username: "BT",
    avatar: "BT",
    aura: 420,
    wins: 8,
    losses: 11,
    winRate: 42,
    rank: "Citizen",
    rankColor: "text-stone-500",
    streak: 0,
    coins: 500,
    badges: [],
    joinDate: "2025-02-14",
  },
  {
    id: "u-10",
    username: "MR",
    avatar: "MR",
    aura: 210,
    wins: 4,
    losses: 9,
    winRate: 31,
    rank: "Citizen",
    rankColor: "text-stone-500",
    streak: 0,
    coins: 250,
    badges: [],
    joinDate: "2025-03-01",
  },
  {
    id: "u-11",
    username: "HS",
    avatar: "HS",
    aura: 80,
    wins: 1,
    losses: 7,
    winRate: 13,
    rank: "Citizen",
    rankColor: "text-stone-500",
    streak: 0,
    coins: 100,
    badges: [],
    joinDate: "2025-04-10",
  },
  {
    id: "u-12",
    username: "RK",
    avatar: "RK",
    aura: 0,
    wins: 0,
    losses: 5,
    winRate: 0,
    rank: "Citizen",
    rankColor: "text-stone-500",
    streak: 0,
    coins: 50,
    badges: [],
    joinDate: "2025-05-01",
  },
];

// ============================================================
// Mock Categories
// ============================================================

export const mockCategories: Category[] = [
  {
    id: "cat-movies",
    name: "Movies",
    icon: "Film",
    battleCount: 1247,
    color: "bg-orange-100 text-orange-700",
  },
  {
    id: "cat-games",
    name: "Games",
    icon: "Gamepad2",
    battleCount: 983,
    color: "bg-[#4D7C0F]/10 text-[#4D7C0F]",
  },
  {
    id: "cat-anime",
    name: "Anime",
    icon: "Sparkles",
    battleCount: 876,
    color: "bg-stone-100 text-stone-700",
  },
  {
    id: "cat-sports",
    name: "Sports",
    icon: "Trophy",
    battleCount: 1102,
    color: "bg-orange-100 text-orange-700",
  },
  {
    id: "cat-food",
    name: "Food",
    icon: "UtensilsCrossed",
    battleCount: 654,
    color: "bg-[#4D7C0F]/10 text-[#4D7C0F]",
  },
  {
    id: "cat-music",
    name: "Music",
    icon: "Music",
    battleCount: 498,
    color: "bg-stone-100 text-stone-700",
  },
  {
    id: "cat-tech",
    name: "Tech",
    icon: "Cpu",
    battleCount: 721,
    color: "bg-orange-100 text-orange-700",
  },
  {
    id: "cat-viral",
    name: "Viral",
    icon: "Flame",
    battleCount: 1534,
    color: "bg-[#4D7C0F]/10 text-[#4D7C0F]",
  },
];

// ============================================================
// Mock Battles
// ============================================================

export const mockBattles: BattleCase[] = [
  // --- Movies ---
  {
    id: "b-1",
    sideA: "Pushpa",
    sideB: "KGF",
    category: "Movies",
    difficulty: "Gold",
    difficultyColor: "bg-yellow-100 text-yellow-700 border-yellow-300",
    teamA: [mockUsers[0], mockUsers[2], mockUsers[4], null, null],
    teamB: [mockUsers[1], mockUsers[3], mockUsers[5], null, null],
    spectators: [mockUsers[7], mockUsers[8], mockUsers[9]],
    maxSpectators: 200,
    status: "live",
    timer: 145,
    totalTimer: 300,
    chatMessages: [
      {
        id: "cm-1",
        userId: "u-1",
        username: "DK",
        text: "Pushpa's character arc is far more compelling — raw, grounded, and emotionally resonant.",
        timestamp: Date.now() - 120000,
        isAi: false,
        type: "argument",
      },
      {
        id: "cm-2",
        userId: "u-2",
        username: "AR",
        text: "KGF has scale, visual grandeur, and a villain who actually steals the show. Adheera alone > entire Pushpa supporting cast.",
        timestamp: Date.now() - 100000,
        isAi: false,
        type: "argument",
      },
      {
        id: "cm-3",
        userId: "ai",
        username: "AI Judge",
        text: "[AI] @MR eliminated — unparliamentary language detected. Stay respectful.",
        timestamp: Date.now() - 80000,
        isAi: true,
        type: "ai_kick",
      },
      {
        id: "cm-4",
        userId: "u-3",
        username: "PS",
        text: "KGF Chapter 2's box office numbers speak for themselves. ₹1200Cr+ worldwide. That's not just hype, that's cultural impact.",
        timestamp: Date.now() - 60000,
        isAi: false,
        type: "argument",
      },
      {
        id: "cm-5",
        userId: "u-7",
        username: "SP",
        text: "🔥🔥🔥 This debate is fire",
        timestamp: Date.now() - 40000,
        isAi: false,
        type: "spectator_reaction",
        reaction: "🔥",
      },
      {
        id: "cm-6",
        userId: "u-4",
        username: "VK",
        text: "Pushpa's dialogue writing is iconic. 'Jhukega Nahi Sala' became a nationwide movement. KGF has nothing that viral.",
        timestamp: Date.now() - 20000,
        isAi: false,
        type: "argument",
      },
    ],
    aiVerdict: null,
    auraStake: 150,
    viewers: 127,
  },
  {
    id: "b-2",
    sideA: "Bhai",
    sideB: "Darling",
    category: "Movies",
    difficulty: "Silver",
    difficultyColor: "bg-stone-100 text-stone-600 border-stone-300",
    teamA: [mockUsers[5], mockUsers[8], null, null, null],
    teamB: [mockUsers[6], mockUsers[10], null, null, null],
    spectators: [mockUsers[11]],
    maxSpectators: 100,
    status: "waiting",
    timer: 180,
    totalTimer: 240,
    chatMessages: [],
    aiVerdict: null,
    auraStake: 80,
    viewers: 34,
  },
  {
    id: "b-3",
    sideA: "Interstellar",
    sideB: "Inception",
    category: "Movies",
    difficulty: "Platinum",
    difficultyColor: "bg-orange-100 text-orange-700 border-orange-300",
    teamA: [mockUsers[0], mockUsers[1], mockUsers[3], mockUsers[6], mockUsers[9]],
    teamB: [mockUsers[2], mockUsers[4], mockUsers[5], mockUsers[7], mockUsers[8]],
    spectators: [mockUsers[10], mockUsers[11]],
    maxSpectators: 300,
    status: "verdict",
    timer: 0,
    totalTimer: 600,
    chatMessages: [
      {
        id: "cm-7",
        userId: "u-1",
        username: "DK",
        text: "Interstellar tackles the most fundamental human emotion — love across dimensions. Nolan's masterpiece of science and soul.",
        timestamp: Date.now() - 300000,
        isAi: false,
        type: "argument",
      },
      {
        id: "cm-8",
        userId: "u-2",
        username: "AR",
        text: "Inception's layered narrative is structurally perfect. Every frame serves the story. It's screenwriting at its absolute finest.",
        timestamp: Date.now() - 280000,
        isAi: false,
        type: "argument",
      },
      {
        id: "cm-9",
        userId: "ai",
        username: "AI Judge",
        text: "[AI] @BT warned — argument lacks substance. Provide evidence or face elimination.",
        timestamp: Date.now() - 260000,
        isAi: true,
        type: "ai_warning",
      },
      {
        id: "cm-10",
        userId: "u-3",
        username: "PS",
        text: "Hans Zimmer's organ score in Interstellar is the greatest film soundtrack ever composed. It carries the entire emotional weight.",
        timestamp: Date.now() - 240000,
        isAi: false,
        type: "argument",
      },
    ],
    aiVerdict: {
      winner: "A",
      scoreA: 87,
      scoreB: 79,
      bestArgument: {
        userId: "u-1",
        username: "DK",
        text: "Interstellar tackles the most fundamental human emotion — love across dimensions. Nolan's masterpiece of science and soul.",
      },
      mostRoasted: {
        userId: "u-8",
        username: "AJ",
        roastCount: 4,
      },
      summary: "Team Interstellar wins by a narrow margin. DK's emotional appeal combined with PS's musical argument created an unbreakable case. Team Inception had stronger structural arguments but lacked the emotional punch needed to sway the AI court.",
      coinsAwarded: 250,
      auraChange: { gained: 180, lost: 120 },
    },
    auraStake: 300,
    viewers: 198,
  },
  {
    id: "b-4",
    sideA: "RRR",
    sideB: "Bahubali",
    category: "Movies",
    difficulty: "Gold",
    difficultyColor: "bg-yellow-100 text-yellow-700 border-yellow-300",
    teamA: [mockUsers[3], mockUsers[7], mockUsers[10], null, null],
    teamB: [mockUsers[4], mockUsers[8], mockUsers[11], null, null],
    spectators: [mockUsers[0], mockUsers[1]],
    maxSpectators: 200,
    status: "finished",
    timer: 0,
    totalTimer: 300,
    chatMessages: [],
    aiVerdict: {
      winner: "A",
      scoreA: 82,
      scoreB: 75,
      bestArgument: {
        userId: "u-4",
        username: "VK",
        text: "RRR proved Indian cinema can create global action spectacles that rival Hollywood. The Oscars spoke for themselves.",
      },
      mostRoasted: {
        userId: "u-12",
        username: "RK",
        roastCount: 2,
      },
      summary: "Team RRR dominated with international recognition arguments. Team Bahubali fought valiantly with scale and legacy points but couldn't overcome the Oscar factor.",
      coinsAwarded: 200,
      auraChange: { gained: 150, lost: 100 },
    },
    auraStake: 150,
    viewers: 156,
  },

  // --- Games ---
  {
    id: "b-5",
    sideA: "GTA",
    sideB: "RDR2",
    category: "Games",
    difficulty: "Gold",
    difficultyColor: "bg-yellow-100 text-yellow-700 border-yellow-300",
    teamA: [mockUsers[1], mockUsers[5], mockUsers[9], null, null],
    teamB: [mockUsers[2], mockUsers[6], mockUsers[10], null, null],
    spectators: [mockUsers[0], mockUsers[3], mockUsers[7]],
    maxSpectators: 200,
    status: "live",
    timer: 210,
    totalTimer: 300,
    chatMessages: [
      {
        id: "cm-11",
        userId: "u-2",
        username: "AR",
        text: "GTA V generated $8.6 BILLION in revenue. It's not just a game, it's an economy.",
        timestamp: Date.now() - 90000,
        isAi: false,
        type: "argument",
      },
      {
        id: "cm-12",
        userId: "u-3",
        username: "PS",
        text: "Revenue ≠ quality. RDR2 is Rockstar's magnum opus — better story, better world, better characters. Period.",
        timestamp: Date.now() - 70000,
        isAi: false,
        type: "argument",
      },
      {
        id: "cm-13",
        userId: "ai",
        username: "AI Judge",
        text: "[AI] @HS eliminated — spamming emojis is not an argument.",
        timestamp: Date.now() - 50000,
        isAi: true,
        type: "ai_kick",
      },
      {
        id: "cm-14",
        userId: "u-8",
        username: "AJ",
        text: "😂😂😂 RDR2 fans crying",
        timestamp: Date.now() - 30000,
        isAi: false,
        type: "spectator_reaction",
        reaction: "😂",
      },
    ],
    aiVerdict: null,
    auraStake: 150,
    viewers: 89,
  },
  {
    id: "b-6",
    sideA: "Minecraft",
    sideB: "Terraria",
    category: "Games",
    difficulty: "Bronze",
    difficultyColor: "bg-orange-50 text-orange-600 border-orange-200",
    teamA: [mockUsers[9], mockUsers[11], null, null, null],
    teamB: [mockUsers[10], mockUsers[8], null, null, null],
    spectators: [],
    maxSpectators: 50,
    status: "waiting",
    timer: 180,
    totalTimer: 180,
    chatMessages: [],
    aiVerdict: null,
    auraStake: 40,
    viewers: 15,
  },
  {
    id: "b-7",
    sideA: "Zelda",
    sideB: "Elden Ring",
    category: "Games",
    difficulty: "Platinum",
    difficultyColor: "bg-orange-100 text-orange-700 border-orange-300",
    teamA: [mockUsers[0], mockUsers[2], mockUsers[4], mockUsers[7], mockUsers[10]],
    teamB: [mockUsers[1], mockUsers[3], mockUsers[5], mockUsers[8], mockUsers[11]],
    spectators: [mockUsers[6], mockUsers[9]],
    maxSpectators: 300,
    status: "finished",
    timer: 0,
    totalTimer: 600,
    chatMessages: [],
    aiVerdict: {
      winner: "B",
      scoreA: 81,
      scoreB: 88,
      bestArgument: {
        userId: "u-2",
        username: "AR",
        text: "Elden Ring redefined the open-world genre. Miyazaki's world-building combined with George R.R. Martin's lore created something unprecedented.",
      },
      mostRoasted: {
        userId: "u-10",
        username: "MR",
        roastCount: 3,
      },
      summary: "Team Elden Ring wins convincingly. The depth of lore, combat complexity, and replayability arguments were overwhelming. Team Zelda's accessibility and polish points were strong but insufficient against the Soulsborne juggernaut.",
      coinsAwarded: 300,
      auraChange: { gained: 220, lost: 150 },
    },
    auraStake: 300,
    viewers: 175,
  },

  // --- Anime ---
  {
    id: "b-8",
    sideA: "Naruto",
    sideB: "Goku",
    category: "Anime",
    difficulty: "Platinum",
    difficultyColor: "bg-orange-100 text-orange-700 border-orange-300",
    teamA: [mockUsers[0], mockUsers[3], mockUsers[5], mockUsers[8], mockUsers[11]],
    teamB: [mockUsers[1], mockUsers[4], mockUsers[6], mockUsers[9], mockUsers[10]],
    spectators: [mockUsers[2], mockUsers[7]],
    maxSpectators: 300,
    status: "live",
    timer: 98,
    totalTimer: 600,
    chatMessages: [
      {
        id: "cm-15",
        userId: "u-1",
        username: "DK",
        text: "Naruto's character development from an outcast to Hokage is the greatest arc in anime history. Goku just... powers up.",
        timestamp: Date.now() - 200000,
        isAi: false,
        type: "argument",
      },
      {
        id: "cm-16",
        userId: "u-2",
        username: "AR",
        text: "Goku's influence spans DECADES and inspired entire genres. Naruto exists because Dragon Ball paved the way.",
        timestamp: Date.now() - 180000,
        isAi: false,
        type: "argument",
      },
      {
        id: "cm-17",
        userId: "u-5",
        username: "RM",
        text: "Naruto's Pain Arc is the single greatest story arc in shonen. Change my mind.",
        timestamp: Date.now() - 150000,
        isAi: false,
        type: "argument",
      },
      {
        id: "cm-18",
        userId: "ai",
        username: "AI Judge",
        text: "[AI] @RK eliminated — low-effort argument. Provide specific examples or evidence.",
        timestamp: Date.now() - 120000,
        isAi: true,
        type: "ai_kick",
      },
      {
        id: "cm-19",
        userId: "u-7",
        username: "SP",
        text: "This is the greatest anime debate of all time 🔥🔥",
        timestamp: Date.now() - 80000,
        isAi: false,
        type: "spectator_reaction",
        reaction: "🔥",
      },
    ],
    aiVerdict: null,
    auraStake: 300,
    viewers: 200,
  },
  {
    id: "b-9",
    sideA: "One Piece",
    sideB: "Demon Slayer",
    category: "Anime",
    difficulty: "Gold",
    difficultyColor: "bg-yellow-100 text-yellow-700 border-yellow-300",
    teamA: [mockUsers[2], mockUsers[6], mockUsers[10], null, null],
    teamB: [mockUsers[5], mockUsers[9], mockUsers[11], null, null],
    spectators: [mockUsers[0], mockUsers[1], mockUsers[4]],
    maxSpectators: 200,
    status: "waiting",
    timer: 240,
    totalTimer: 300,
    chatMessages: [],
    aiVerdict: null,
    auraStake: 150,
    viewers: 72,
  },
  {
    id: "b-10",
    sideA: "AOT",
    sideB: "JJK",
    category: "Anime",
    difficulty: "Silver",
    difficultyColor: "bg-stone-100 text-stone-600 border-stone-300",
    teamA: [mockUsers[4], mockUsers[7], mockUsers[8], null, null],
    teamB: [mockUsers[6], mockUsers[9], null, null, null],
    spectators: [mockUsers[3], mockUsers[10]],
    maxSpectators: 100,
    status: "finished",
    timer: 0,
    totalTimer: 240,
    chatMessages: [],
    aiVerdict: {
      winner: "A",
      scoreA: 85,
      scoreB: 71,
      bestArgument: {
        userId: "u-5",
        username: "RM",
        text: "Attack on Titan's plot twists are genuinely unpredictable. The basement reveal, the time skip, the ending — no anime has matched that level of narrative ambition.",
      },
      mostRoasted: {
        userId: "u-9",
        username: "BT",
        roastCount: 2,
      },
      summary: "Team AOT dominated with narrative depth and cultural impact arguments. Team JJK's animation quality and fight choreography points were acknowledged but ultimately insufficient against AOT's storytelling legacy.",
      coinsAwarded: 150,
      auraChange: { gained: 100, lost: 70 },
    },
    auraStake: 80,
    viewers: 43,
  },

  // --- Sports ---
  {
    id: "b-11",
    sideA: "Messi",
    sideB: "Ronaldo",
    category: "Sports",
    difficulty: "Platinum",
    difficultyColor: "bg-orange-100 text-orange-700 border-orange-300",
    teamA: [mockUsers[0], mockUsers[2], mockUsers[4], mockUsers[6], mockUsers[8]],
    teamB: [mockUsers[1], mockUsers[3], mockUsers[5], mockUsers[7], mockUsers[9]],
    spectators: [mockUsers[10], mockUsers[11]],
    maxSpectators: 500,
    status: "live",
    timer: 320,
    totalTimer: 600,
    chatMessages: [
      {
        id: "cm-20",
        userId: "u-1",
        username: "DK",
        text: "8 Ballon d'Ors. World Cup winner. The most trophies in football history. Numbers don't lie.",
        timestamp: Date.now() - 250000,
        isAi: false,
        type: "argument",
      },
      {
        id: "cm-21",
        userId: "u-2",
        username: "AR",
        text: "Ronaldo proved himself in 4 different leagues. Premier League, La Liga, Serie A, Ligue 1. Messi stayed in his comfort zone.",
        timestamp: Date.now() - 220000,
        isAi: false,
        type: "argument",
      },
      {
        id: "cm-22",
        userId: "u-4",
        username: "VK",
        text: "Champions League top scorer of all time. In the biggest games, Ronaldo shows up. That's clutch DNA.",
        timestamp: Date.now() - 180000,
        isAi: false,
        type: "argument",
      },
      {
        id: "cm-23",
        userId: "ai",
        username: "AI Judge",
        text: "[AI] @MR eliminated — personal attacks are not arguments. Debate the topic, not the person.",
        timestamp: Date.now() - 140000,
        isAi: true,
        type: "ai_kick",
      },
      {
        id: "cm-24",
        userId: "u-3",
        username: "PS",
        text: "The World Cup is the ultimate prize in football. Messi has it. Ronaldo doesn't. Case closed for international football.",
        timestamp: Date.now() - 100000,
        isAi: false,
        type: "argument",
      },
      {
        id: "cm-25",
        userId: "u-8",
        username: "AJ",
        text: "GOAT debate will never end 😭😭",
        timestamp: Date.now() - 60000,
        isAi: false,
        type: "spectator_reaction",
        reaction: "😭",
      },
    ],
    aiVerdict: null,
    auraStake: 400,
    viewers: 342,
  },
  {
    id: "b-12",
    sideA: "India",
    sideB: "Pakistan",
    category: "Sports",
    difficulty: "Gold",
    difficultyColor: "bg-yellow-100 text-yellow-700 border-yellow-300",
    teamA: [mockUsers[0], mockUsers[3], mockUsers[7], null, null],
    teamB: [mockUsers[1], mockUsers[4], mockUsers[8], null, null],
    spectators: [mockUsers[2], mockUsers[5], mockUsers[9], mockUsers[10], mockUsers[11]],
    maxSpectators: 500,
    status: "finished",
    timer: 0,
    totalTimer: 300,
    chatMessages: [],
    aiVerdict: {
      winner: "A",
      scoreA: 78,
      scoreB: 72,
      bestArgument: {
        userId: "u-1",
        username: "DK",
        text: "India's ICC tournament record speaks for itself — 4 World Cups, 2 T20 World Cups, 3 Champions Trophies. Consistent dominance across formats.",
      },
      mostRoasted: {
        userId: "u-11",
        username: "HS",
        roastCount: 3,
      },
      summary: "Team India wins on consistent ICC tournament performance. Team Pakistan had strong arguments in individual matchups and bowling attacks, but India's overall trophy cabinet proved decisive.",
      coinsAwarded: 200,
      auraChange: { gained: 140, lost: 95 },
    },
    auraStake: 200,
    viewers: 287,
  },
  {
    id: "b-13",
    sideA: "Federer",
    sideB: "Nadal",
    category: "Sports",
    difficulty: "Silver",
    difficultyColor: "bg-stone-100 text-stone-600 border-stone-300",
    teamA: [mockUsers[5], mockUsers[8], null, null, null],
    teamB: [mockUsers[6], mockUsers[9], null, null, null],
    spectators: [mockUsers[0]],
    maxSpectators: 100,
    status: "waiting",
    timer: 180,
    totalTimer: 240,
    chatMessages: [],
    aiVerdict: null,
    auraStake: 80,
    viewers: 28,
  },

  // --- Food ---
  {
    id: "b-14",
    sideA: "Biryani",
    sideB: "Pizza",
    category: "Food",
    difficulty: "Bronze",
    difficultyColor: "bg-orange-50 text-orange-600 border-orange-200",
    teamA: [mockUsers[7], mockUsers[10], null, null, null],
    teamB: [mockUsers[8], mockUsers[11], null, null, null],
    spectators: [],
    maxSpectators: 50,
    status: "waiting",
    timer: 120,
    totalTimer: 180,
    chatMessages: [],
    aiVerdict: null,
    auraStake: 40,
    viewers: 22,
  },
  {
    id: "b-15",
    sideA: "North Indian",
    sideB: "South Indian",
    category: "Food",
    difficulty: "Silver",
    difficultyColor: "bg-stone-100 text-stone-600 border-stone-300",
    teamA: [mockUsers[4], mockUsers[9], mockUsers[11], null, null],
    teamB: [mockUsers[5], mockUsers[10], null, null, null],
    spectators: [mockUsers[3]],
    maxSpectators: 100,
    status: "finished",
    timer: 0,
    totalTimer: 240,
    chatMessages: [],
    aiVerdict: {
      winner: "B",
      scoreA: 73,
      scoreB: 80,
      bestArgument: {
        userId: "u-6",
        username: "NK",
        text: "South Indian cuisine is recognized by UNESCO. Dosa, idli, sambar — it's not just food, it's heritage with incredible nutritional balance.",
      },
      mostRoasted: {
        userId: "u-12",
        username: "RK",
        roastCount: 1,
      },
      summary: "Team South Indian wins with health, heritage, and variety arguments. Team North Indian's richness and Mughlai influence points were strong but couldn't overcome the nutritional and cultural depth presented.",
      coinsAwarded: 120,
      auraChange: { gained: 85, lost: 55 },
    },
    auraStake: 80,
    viewers: 56,
  },

  // --- Music ---
  {
    id: "b-16",
    sideA: "Arijit",
    sideB: "Atif",
    category: "Music",
    difficulty: "Gold",
    difficultyColor: "bg-yellow-100 text-yellow-700 border-yellow-300",
    teamA: [mockUsers[2], mockUsers[6], mockUsers[9], null, null],
    teamB: [mockUsers[3], mockUsers[7], mockUsers[10], null, null],
    spectators: [mockUsers[0], mockUsers[1], mockUsers[4]],
    maxSpectators: 200,
    status: "live",
    timer: 170,
    totalTimer: 300,
    chatMessages: [
      {
        id: "cm-26",
        userId: "u-3",
        username: "PS",
        text: "Arijit Singh has the most streamed songs on Spotify India. The man IS modern Indian music.",
        timestamp: Date.now() - 130000,
        isAi: false,
        type: "argument",
      },
      {
        id: "cm-27",
        userId: "u-4",
        username: "VK",
        text: "Atif Aslam crossed borders. His concerts in India sell out in minutes. Cross-border appeal = greater impact.",
        timestamp: Date.now() - 110000,
        isAi: false,
        type: "argument",
      },
      {
        id: "cm-28",
        userId: "u-9",
        username: "BT",
        text: "Both legends ngl 🎵🎵",
        timestamp: Date.now() - 80000,
        isAi: false,
        type: "spectator_reaction",
        reaction: "🎵",
      },
    ],
    aiVerdict: null,
    auraStake: 150,
    viewers: 94,
  },
  {
    id: "b-17",
    sideA: "Rap",
    sideB: "Lo-fi",
    category: "Music",
    difficulty: "Silver",
    difficultyColor: "bg-stone-100 text-stone-600 border-stone-300",
    teamA: [mockUsers[8], mockUsers[11], null, null, null],
    teamB: [mockUsers[9], mockUsers[10], null, null, null],
    spectators: [mockUsers[5]],
    maxSpectators: 100,
    status: "waiting",
    timer: 180,
    totalTimer: 240,
    chatMessages: [],
    aiVerdict: null,
    auraStake: 80,
    viewers: 31,
  },

  // --- Tech ---
  {
    id: "b-18",
    sideA: "Apple",
    sideB: "Android",
    category: "Tech",
    difficulty: "Gold",
    difficultyColor: "bg-yellow-100 text-yellow-700 border-yellow-300",
    teamA: [mockUsers[1], mockUsers[4], mockUsers[8], null, null],
    teamB: [mockUsers[2], mockUsers[5], mockUsers[9], null, null],
    spectators: [mockUsers[0], mockUsers[3], mockUsers[6], mockUsers[7]],
    maxSpectators: 200,
    status: "finished",
    timer: 0,
    totalTimer: 300,
    chatMessages: [],
    aiVerdict: {
      winner: "B",
      scoreA: 76,
      scoreB: 83,
      bestArgument: {
        userId: "u-3",
        username: "PS",
        text: "Android powers 72% of global smartphones. Open source, customizable, and accessible across all price points. It's democracy in tech.",
      },
      mostRoasted: {
        userId: "u-10",
        username: "MR",
        roastCount: 2,
      },
      summary: "Team Android wins with market dominance, openness, and accessibility arguments. Team Apple's ecosystem, privacy, and premium experience points were acknowledged but the global reach argument was decisive.",
      coinsAwarded: 180,
      auraChange: { gained: 130, lost: 90 },
    },
    auraStake: 150,
    viewers: 145,
  },
  {
    id: "b-19",
    sideA: "PC",
    sideB: "Console",
    category: "Tech",
    difficulty: "Silver",
    difficultyColor: "bg-stone-100 text-stone-600 border-stone-300",
    teamA: [mockUsers[3], mockUsers[7], mockUsers[11], null, null],
    teamB: [mockUsers[4], mockUsers[8], null, null, null],
    spectators: [mockUsers[1], mockUsers[2]],
    maxSpectators: 100,
    status: "live",
    timer: 88,
    totalTimer: 240,
    chatMessages: [
      {
        id: "cm-29",
        userId: "u-4",
        username: "VK",
        text: "PC gaming has mods, better graphics, and cheaper games in the long run. Steam sales alone save thousands.",
        timestamp: Date.now() - 100000,
        isAi: false,
        type: "argument",
      },
      {
        id: "cm-30",
        userId: "u-5",
        username: "RM",
        text: "Consoles deliver consistent performance at a fixed price. No driver issues, no compatibility problems. Plug and play.",
        timestamp: Date.now() - 75000,
        isAi: false,
        type: "argument",
      },
      {
        id: "cm-31",
        userId: "ai",
        username: "AI Judge",
        text: "[AI] @HS warned — personal attack on other debater. Keep it professional.",
        timestamp: Date.now() - 50000,
        isAi: true,
        type: "ai_warning",
      },
    ],
    aiVerdict: null,
    auraStake: 80,
    viewers: 67,
  },

  // --- Viral ---
  {
    id: "b-20",
    sideA: "Flat Earth",
    sideB: "Round Earth",
    category: "Viral",
    difficulty: "Bronze",
    difficultyColor: "bg-orange-50 text-orange-600 border-orange-200",
    teamA: [mockUsers[10], mockUsers[11], null, null, null],
    teamB: [mockUsers[7], mockUsers[8], mockUsers[9], null, null],
    spectators: [mockUsers[0], mockUsers[1], mockUsers[2], mockUsers[3], mockUsers[4], mockUsers[5]],
    maxSpectators: 100,
    status: "live",
    timer: 55,
    totalTimer: 180,
    chatMessages: [
      {
        id: "cm-32",
        userId: "u-8",
        username: "AJ",
        text: "There are literally satellite photos. The Earth is round. This debate shouldn't exist.",
        timestamp: Date.now() - 60000,
        isAi: false,
        type: "argument",
      },
      {
        id: "cm-33",
        userId: "u-10",
        username: "MR",
        text: "Water always finds its level. If Earth were spinning at 1000mph, we'd feel it. Wake up.",
        timestamp: Date.now() - 45000,
        isAi: false,
        type: "argument",
      },
      {
        id: "cm-34",
        userId: "u-1",
        username: "DK",
        text: "💀💀💀 I can't with this debate",
        timestamp: Date.now() - 30000,
        isAi: false,
        type: "spectator_reaction",
        reaction: "💀",
      },
      {
        id: "cm-35",
        userId: "u-2",
        username: "AR",
        text: "😂😂😂 This is entertainment at its finest",
        timestamp: Date.now() - 15000,
        isAi: false,
        type: "spectator_reaction",
        reaction: "😂",
      },
    ],
    aiVerdict: null,
    auraStake: 40,
    viewers: 156,
  },
  {
    id: "b-21",
    sideA: "Aliens Real",
    sideB: "Aliens Not Real",
    category: "Viral",
    difficulty: "Silver",
    difficultyColor: "bg-stone-100 text-stone-600 border-stone-300",
    teamA: [mockUsers[5], mockUsers[8], mockUsers[11], null, null],
    teamB: [mockUsers[6], mockUsers[9], mockUsers[10], null, null],
    spectators: [mockUsers[0], mockUsers[2], mockUsers[4]],
    maxSpectators: 100,
    status: "waiting",
    timer: 240,
    totalTimer: 240,
    chatMessages: [],
    aiVerdict: null,
    auraStake: 80,
    viewers: 48,
  },
];

// ============================================================
// Mock Quests
// ============================================================

export const mockQuests: Quest[] = [
  {
    id: "q-1",
    title: "Win 2 Battles",
    description: "Win 2 battles to earn rewards and boost your aura.",
    progress: 1,
    target: 2,
    reward: { coins: 100, aura: 50 },
    completed: false,
  },
  {
    id: "q-2",
    title: "Argue in 3 Categories",
    description: "Participate in battles across 3 different categories.",
    progress: 2,
    target: 3,
    reward: { coins: 150, aura: 75 },
    completed: false,
  },
  {
    id: "q-3",
    title: "Zero AI Kicks",
    description: "Complete a full battle without receiving a single AI warning or kick.",
    progress: 1,
    target: 1,
    reward: { coins: 200, aura: 100 },
    completed: true,
  },
  {
    id: "q-4",
    title: "Spectate 5 Battles",
    description: "Watch 5 battles as a spectator to expand your knowledge.",
    progress: 3,
    target: 5,
    reward: { coins: 75, aura: 25 },
    completed: false,
  },
];

// ============================================================
// Mock Marketplace Items
// ============================================================

export const mockMarketplaceItems: MarketplaceItem[] = [
  {
    id: "mp-1",
    name: "Fire Frame",
    type: "frame",
    cost: 500,
    rarity: "rare",
    rarityColor: "text-blue-500",
    owned: true,
    equipped: false,
  },
  {
    id: "mp-2",
    name: "Olive Crown",
    type: "frame",
    cost: 1200,
    rarity: "epic",
    rarityColor: "text-purple-500",
    owned: false,
    equipped: false,
  },
  {
    id: "mp-3",
    name: "The Roast King",
    type: "title",
    cost: 800,
    rarity: "rare",
    rarityColor: "text-blue-500",
    owned: true,
    equipped: true,
  },
  {
    id: "mp-4",
    name: "Supreme Judge",
    type: "title",
    cost: 2000,
    rarity: "legendary",
    rarityColor: "text-orange-600",
    owned: false,
    equipped: false,
  },
  {
    id: "mp-5",
    name: "Case Closer",
    type: "title",
    cost: 400,
    rarity: "common",
    rarityColor: "text-stone-500",
    owned: true,
    equipped: false,
  },
  {
    id: "mp-6",
    name: "Hot Streak",
    type: "badge",
    cost: 600,
    rarity: "rare",
    rarityColor: "text-blue-500",
    owned: false,
    equipped: false,
  },
  {
    id: "mp-7",
    name: "Crowd Favorite",
    type: "badge",
    cost: 1500,
    rarity: "epic",
    rarityColor: "text-purple-500",
    owned: false,
    equipped: false,
  },
  {
    id: "mp-8",
    name: "Aura Glow",
    type: "effect",
    cost: 3000,
    rarity: "legendary",
    rarityColor: "text-orange-600",
    owned: false,
    equipped: false,
  },
];

// ============================================================
// Mock Groups
// ============================================================

export const mockGroups: GroupInfo[] = [
  {
    id: "g-1",
    name: "Movie Maniacs",
    members: 342,
    description: "The ultimate battleground for cinema debates. From Bollywood blockbusters to Hollywood classics.",
    category: "Movies",
    isJoined: true,
  },
  {
    id: "g-2",
    name: "Anime Army",
    members: 521,
    description: "For those who live and breathe anime. Shonen supremacy, isekai debates, and waifu wars.",
    category: "Anime",
    isJoined: true,
  },
  {
    id: "g-3",
    name: "Game Lords",
    members: 289,
    description: "PC master race vs console peasants. Nintendo vs Sony vs Xbox. All gaming debates welcome.",
    category: "Games",
    isJoined: true,
  },
  {
    id: "g-4",
    name: "Food Fighters",
    members: 178,
    description: "Biryani or pizza? Chai or coffee? Settle the food debates that divide nations.",
    category: "Food",
    isJoined: false,
  },
  {
    id: "g-5",
    name: "Sports Squad",
    members: 415,
    description: "GOAT debates, match predictions, and legendary sporting rivalries. Cricket, football, and more.",
    category: "Sports",
    isJoined: false,
  },
  {
    id: "g-6",
    name: "Tech Titans",
    members: 256,
    description: "Apple vs Android, PC vs Console, AI vs Humans. The future is debated here.",
    category: "Tech",
    isJoined: false,
  },
];