// ============================================================
// Verdict — Mock Data Layer
// ============================================================

export interface User {
  id: string;
  username: string;
  avatar: string;
  aura: number;
  wins: number;
  losses: number;
  winRate: number;
  rank: string;
  rankColor: string;
  streak: number;
  coins: number;
  badges: string[];
  joinDate: string;
  ownedItemIds: string[];
  equippedItemIds: string[];
}

export interface BattleCase {
  id: string;
  sideA: string;
  sideB: string;
  category: string;
  difficulty: "Bronze" | "Silver" | "Gold" | "Platinum";
  difficultyColor: string;
  teamA: (User | null)[];
  teamB: (User | null)[];
  spectators: User[];
  maxSpectators: number;
  status: "waiting" | "live" | "verdict" | "finished";
  timer: number;
  totalTimer: number;
  chatMessages: ChatMessage[];
  aiVerdict: AiVerdict | null;
  auraStake: number;
  viewers: number;
}

export interface ChatMessage {
  id: string;
  userId: string;
  username: string;
  text: string;
  timestamp: number;
  isAi: boolean;
  type: "argument" | "ai_kick" | "ai_warning" | "spectator_reaction" | "system";
  reaction?: string;
}

export interface AiVerdict {
  winner: "A" | "B";
  scoreA: number;
  scoreB: number;
  bestArgument: { userId: string; username: string; text: string };
  mostRoasted: { userId: string; username: string; roastCount: number };
  summary: string;
  coinsAwarded: number;
  auraChange: { gained: number; lost: number };
}

export interface Category {
  id: string;
  name: string;
  icon: string;
  battleCount: number;
  color: string;
}

export interface Quest {
  id: string;
  title: string;
  description: string;
  progress: number;
  target: number;
  reward: { coins: number; aura: number };
  completed: boolean;
  claimed: boolean;
}

export interface MarketplaceItem {
  id: string;
  name: string;
  type: "frame" | "title" | "badge" | "effect";
  cost: number;
  rarity: "common" | "rare" | "epic" | "legendary";
  rarityColor: string;
  owned: boolean;
  equipped: boolean;
  previewType: "border" | "text" | "icon" | "description";
  description: string;
}

export interface GroupInfo {
  id: string;
  name: string;
  members: number;
  description: string;
  category: string;
  isJoined: boolean;
}

// ============================================================
// Mock Users
// ============================================================

export const mockCurrentUser: User = {
  id: "u-me",
  username: "You",
  avatar: "YO",
  aura: 1250,
  wins: 18,
  losses: 12,
  winRate: 60,
  rank: "Flame Thrower",
  rankColor: "text-red-500",
  streak: 3,
  coins: 850,
  badges: ["Flame Streak", "Roast Master"],
  joinDate: "2025-01-15",
  ownedItemIds: ["mp-1", "mp-3", "mp-5"],
  equippedItemIds: ["mp-3"],
};

export const mockUsers: User[] = [
  {
    id: "u-1",
    username: "DK",
    avatar: "DK",
    aura: 5200,
    wins: 94,
    losses: 21,
    winRate: 82,
    rank: "Dragon",
    rankColor: "text-red-500",
    streak: 12,
    coins: 12400,
    badges: ["Top 10", "Flame Streak", "Roast Master", "Unstoppable"],
    joinDate: "2024-06-10",
    ownedItemIds: [],
    equippedItemIds: [],
  },
  {
    id: "u-2",
    username: "AR",
    avatar: "AR",
    aura: 3850,
    wins: 67,
    losses: 28,
    winRate: 71,
    rank: "Inferno",
    rankColor: "text-amber-400",
    streak: 5,
    coins: 8200,
    badges: ["Top 10", "Roast Master"],
    joinDate: "2024-08-22",
    ownedItemIds: [],
    equippedItemIds: [],
  },
  {
    id: "u-3",
    username: "PS",
    avatar: "PS",
    aura: 2940,
    wins: 52,
    losses: 30,
    winRate: 63,
    rank: "Blaze Lord",
    rankColor: "text-zinc-300",
    streak: 2,
    coins: 5600,
    badges: ["Roast Master"],
    joinDate: "2024-09-05",
    ownedItemIds: [],
    equippedItemIds: [],
  },
  {
    id: "u-4",
    username: "VK",
    avatar: "VK",
    aura: 2100,
    wins: 41,
    losses: 22,
    winRate: 65,
    rank: "Blaze Lord",
    rankColor: "text-zinc-300",
    streak: 4,
    coins: 4300,
    badges: ["Flame Streak"],
    joinDate: "2024-10-12",
    ownedItemIds: [],
    equippedItemIds: [],
  },
  {
    id: "u-5",
    username: "RM",
    avatar: "RM",
    aura: 1750,
    wins: 35,
    losses: 20,
    winRate: 64,
    rank: "Flame Thrower",
    rankColor: "text-red-500",
    streak: 1,
    coins: 3200,
    badges: [],
    joinDate: "2024-11-01",
    ownedItemIds: [],
    equippedItemIds: [],
  },
  {
    id: "u-6",
    username: "NK",
    avatar: "NK",
    aura: 1320,
    wins: 28,
    losses: 18,
    winRate: 61,
    rank: "Flame Thrower",
    rankColor: "text-red-500",
    streak: 3,
    coins: 2100,
    badges: ["Roast Master"],
    joinDate: "2024-11-20",
    ownedItemIds: [],
    equippedItemIds: [],
  },
  {
    id: "u-7",
    username: "SP",
    avatar: "SP",
    aura: 980,
    wins: 19,
    losses: 16,
    winRate: 54,
    rank: "Flame Thrower",
    rankColor: "text-red-500",
    streak: 0,
    coins: 1400,
    badges: [],
    joinDate: "2024-12-05",
    ownedItemIds: [],
    equippedItemIds: [],
  },
  {
    id: "u-8",
    username: "AJ",
    avatar: "AJ",
    aura: 640,
    wins: 12,
    losses: 14,
    winRate: 46,
    rank: "Spark",
    rankColor: "text-zinc-500",
    streak: 1,
    coins: 800,
    badges: [],
    joinDate: "2025-01-08",
    ownedItemIds: [],
    equippedItemIds: [],
  },
  {
    id: "u-9",
    username: "BT",
    avatar: "BT",
    aura: 420,
    wins: 8,
    losses: 11,
    winRate: 42,
    rank: "Spark",
    rankColor: "text-zinc-500",
    streak: 0,
    coins: 500,
    badges: [],
    joinDate: "2025-02-14",
    ownedItemIds: [],
    equippedItemIds: [],
  },
  {
    id: "u-10",
    username: "MR",
    avatar: "MR",
    aura: 210,
    wins: 4,
    losses: 9,
    winRate: 31,
    rank: "Spark",
    rankColor: "text-zinc-500",
    streak: 0,
    coins: 250,
    badges: [],
    joinDate: "2025-03-01",
    ownedItemIds: [],
    equippedItemIds: [],
  },
  {
    id: "u-11",
    username: "HS",
    avatar: "HS",
    aura: 80,
    wins: 1,
    losses: 7,
    winRate: 13,
    rank: "Spark",
    rankColor: "text-zinc-500",
    streak: 0,
    coins: 100,
    badges: [],
    joinDate: "2025-04-10",
    ownedItemIds: [],
    equippedItemIds: [],
  },
  {
    id: "u-12",
    username: "RK",
    avatar: "RK",
    aura: 0,
    wins: 0,
    losses: 5,
    winRate: 0,
    rank: "Spark",
    rankColor: "text-zinc-500",
    streak: 0,
    coins: 50,
    badges: [],
    joinDate: "2025-05-01",
    ownedItemIds: [],
    equippedItemIds: [],
  },
];

// ============================================================
// Mock Categories
// ============================================================

export const mockCategories: Category[] = [
  {
    id: "cat-movies",
    name: "Movies",
    icon: "Film",
    battleCount: 1247,
    color: "bg-orange-600/15 text-orange-400",
  },
  {
    id: "cat-games",
    name: "Games",
    icon: "Gamepad2",
    battleCount: 983,
    color: "bg-[#4D7C0F]/20 text-[#4D7C0F]",
  },
  {
    id: "cat-anime",
    name: "Anime",
    icon: "Sparkles",
    battleCount: 876,
    color: "bg-red-600/15 text-red-400",
  },
  {
    id: "cat-cartoons",
    name: "Cartoons",
    icon: "Tv",
    battleCount: 643,
    color: "bg-yellow-600/15 text-yellow-400",
  },
  {
    id: "cat-sports",
    name: "Sports",
    icon: "Trophy",
    battleCount: 1102,
    color: "bg-orange-600/15 text-orange-400",
  },
  {
    id: "cat-food",
    name: "Food",
    icon: "UtensilsCrossed",
    battleCount: 654,
    color: "bg-[#4D7C0F]/20 text-[#4D7C0F]",
  },
  {
    id: "cat-music",
    name: "Music",
    icon: "Music",
    battleCount: 498,
    color: "bg-amber-600/15 text-amber-400",
  },
  {
    id: "cat-tech",
    name: "Tech",
    icon: "Cpu",
    battleCount: 721,
    color: "bg-emerald-600/15 text-emerald-400",
  },
  {
    id: "cat-viral",
    name: "Viral",
    icon: "Flame",
    battleCount: 1534,
    color: "bg-red-600/15 text-red-400",
  },
];

// ============================================================
// Mock Battles
// ============================================================

export const mockBattles: BattleCase[] = [
  // --- Movies ---
  {
    id: "b-1",
    sideA: "Pushpa",
    sideB: "KGF",
    category: "Movies",
    difficulty: "Gold",
    difficultyColor: "text-red-400",
    teamA: [mockUsers[0], mockUsers[2], mockUsers[4], null, null],
    teamB: [mockUsers[1], mockUsers[3], mockUsers[5], null, null],
    spectators: [mockUsers[7], mockUsers[8], mockUsers[9]],
    maxSpectators: 200,
    status: "live",
    timer: 145,
    totalTimer: 300,
    chatMessages: [
      {
        id: "cm-1",
        userId: "u-1",
        username: "DK",
        text: "Pushpa's character arc eats KGF for breakfast. Raw, grounded, and every line hits harder than Adheera's entire personality.",
        timestamp: Date.now() - 120000,
        isAi: false,
        type: "argument",
      },
      {
        id: "cm-2",
        userId: "u-2",
        username: "AR",
        text: "KGF has scale? Sure. But so does a PowerPoint presentation. Pushpa made a whole nation say 'Jhukega Nahi' while KGF made people say 'nice VFX bro'",
        timestamp: Date.now() - 100000,
        isAi: false,
        type: "argument",
      },
      {
        id: "cm-3",
        userId: "ai",
        username: "AI Roastmaster",
        text: "[Roastmaster] @MR eliminated — unparliamentary language detected. Stay respectful.",
        timestamp: Date.now() - 80000,
        isAi: true,
        type: "ai_kick",
      },
      {
        id: "cm-4",
        userId: "u-3",
        username: "PS",
        text: "KGF made ₹1200Cr and still couldn't make a villain half as memorable as Bhanwar Singh. Rocky had daddy issues, Pushpa had SWAG issues. Big difference.",
        timestamp: Date.now() - 60000,
        isAi: false,
        type: "argument",
      },
      {
        id: "cm-5",
        userId: "u-7",
        username: "SP",
        text: "🔥🔥🔥 KGF team is SILENT right now lmaooo",
        timestamp: Date.now() - 40000,
        isAi: false,
        type: "spectator_reaction",
        reaction: "🔥",
      },
      {
        id: "cm-6",
        userId: "u-4",
        username: "VK",
        text: "Pushpa's dialogue writing is so iconic it made a roadside smuggler a national hero. KGF's Rocky needed 2 chapters and a mountain of gold just to be interesting.",
        timestamp: Date.now() - 20000,
        isAi: false,
        type: "argument",
      },
    ],
    aiVerdict: null,
    auraStake: 150,
    viewers: 127,
  },
  {
    id: "b-2",
    sideA: "Bhai",
    sideB: "Darling",
    category: "Movies",
    difficulty: "Silver",
    difficultyColor: "text-zinc-400",
    teamA: [mockUsers[5], mockUsers[8], null, null, null],
    teamB: [mockUsers[6], mockUsers[10], null, null, null],
    spectators: [mockUsers[11]],
    maxSpectators: 100,
    status: "waiting",
    timer: 180,
    totalTimer: 240,
    chatMessages: [],
    aiVerdict: null,
    auraStake: 80,
    viewers: 34,
  },
  {
    id: "b-3",
    sideA: "Interstellar",
    sideB: "Inception",
    category: "Movies",
    difficulty: "Platinum",
    difficultyColor: "text-amber-400",
    teamA: [mockUsers[0], mockUsers[1], mockUsers[3], mockUsers[6], mockUsers[9]],
    teamB: [mockUsers[2], mockUsers[4], mockUsers[5], mockUsers[7], mockUsers[8]],
    spectators: [mockUsers[10], mockUsers[11]],
    maxSpectators: 300,
    status: "verdict",
    timer: 0,
    totalTimer: 600,
    chatMessages: [
      {
        id: "cm-7",
        userId: "u-1",
        username: "DK",
        text: "Interstellar made grown men cry in theatres. Inception made people go 'huh, that was neat.' One film breaks your heart, the other just breaks your brain — temporarily.",
        timestamp: Date.now() - 300000,
        isAi: false,
        type: "argument",
      },
      {
        id: "cm-8",
        userId: "u-2",
        username: "AR",
        text: "Inception's layered narrative is so airtight, film students are STILL writing essays about it. Interstellar's 'love transcends dimensions' is beautiful but let's be real — it's Nolan hand-waving the science away.",
        timestamp: Date.now() - 280000,
        isAi: false,
        type: "argument",
      },
      {
        id: "cm-9",
        userId: "ai",
        username: "AI Roastmaster",
        text: "[Roastmaster] @BT warned — argument lacks substance. Provide evidence or face elimination.",
        timestamp: Date.now() - 260000,
        isAi: true,
        type: "ai_warning",
      },
      {
        id: "cm-10",
        userId: "u-3",
        username: "PS",
        text: "Hans Zimmer's organ score in Interstellar literally vibrates your soul. Inception's BWAAAH is iconic but Interstellar's soundtrack IS the emotional backbone of cinema.",
        timestamp: Date.now() - 240000,
        isAi: false,
        type: "argument",
      },
    ],
    aiVerdict: {
      winner: "A",
      scoreA: 87,
      scoreB: 79,
      bestArgument: {
        userId: "u-1",
        username: "DK",
        text: "Interstellar made grown men cry in theatres. Inception made people go 'huh, that was neat.' One film breaks your heart, the other just breaks your brain — temporarily.",
      },
      mostRoasted: {
        userId: "u-8",
        username: "AJ",
        roastCount: 4,
      },
      summary: "Team Interstellar roasted Inception's 'smart but soulless' reputation. DK's emotional appeal incinerated Team Inception's structural arguments — turns out, you can't quantify feelings with a spinning top.",
      coinsAwarded: 250,
      auraChange: { gained: 180, lost: 120 },
    },
    auraStake: 300,
    viewers: 198,
  },
  {
    id: "b-4",
    sideA: "RRR",
    sideB: "Bahubali",
    category: "Movies",
    difficulty: "Gold",
    difficultyColor: "text-red-400",
    teamA: [mockUsers[3], mockUsers[7], mockUsers[10], null, null],
    teamB: [mockUsers[4], mockUsers[8], mockUsers[11], null, null],
    spectators: [mockUsers[0], mockUsers[1]],
    maxSpectators: 200,
    status: "finished",
    timer: 0,
    totalTimer: 300,
    chatMessages: [],
    aiVerdict: {
      winner: "A",
      scoreA: 82,
      scoreB: 75,
      bestArgument: {
        userId: "u-4",
        username: "VK",
        text: "RRR proved Indian cinema can create global action spectacles that rival Hollywood. The Oscars spoke for themselves.",
      },
      mostRoasted: {
        userId: "u-12",
        username: "RK",
        roastCount: 2,
      },
      summary: "Team RRR brought the Oscars to the roast and Team Bahubali had no comeback. 'But scale!' they cried, while RRR flexed Hollywood validation. Naatu Naatu hit harder than any war sequence Bahubali ever choreographed.",
      coinsAwarded: 200,
      auraChange: { gained: 150, lost: 100 },
    },
    auraStake: 150,
    viewers: 156,
  },

  // --- Games ---
  {
    id: "b-5",
    sideA: "GTA",
    sideB: "RDR2",
    category: "Games",
    difficulty: "Gold",
    difficultyColor: "text-red-400",
    teamA: [mockUsers[1], mockUsers[5], mockUsers[9], null, null],
    teamB: [mockUsers[2], mockUsers[6], mockUsers[10], null, null],
    spectators: [mockUsers[0], mockUsers[3], mockUsers[7]],
    maxSpectators: 200,
    status: "live",
    timer: 210,
    totalTimer: 300,
    chatMessages: [
      {
        id: "cm-11",
        userId: "u-2",
        username: "AR",
        text: "GTA V made $8.6 BILLION. It printed more money than most countries' GDP. RDR2 is art? Cool, GTA is an economy.",
        timestamp: Date.now() - 90000,
        isAi: false,
        type: "argument",
      },
      {
        id: "cm-12",
        userId: "u-3",
        username: "PS",
        text: "Revenue ≠ quality, that's the kind of take a CEO makes. RDR2 is Rockstar's magnum opus — better story, better world, better characters. GTA is a sandbox, RDR2 is a masterpiece.",
        timestamp: Date.now() - 70000,
        isAi: false,
        type: "argument",
      },
      {
        id: "cm-13",
        userId: "ai",
        username: "AI Roastmaster",
        text: "[Roastmaster] @HS eliminated — spamming emojis is not an argument.",
        timestamp: Date.now() - 50000,
        isAi: true,
        type: "ai_kick",
      },
      {
        id: "cm-14",
        userId: "u-8",
        username: "AJ",
        text: "😂😂😂 GTA team really brought a SPREADSHEET to a roast battle",
        timestamp: Date.now() - 30000,
        isAi: false,
        type: "spectator_reaction",
        reaction: "😂",
      },
    ],
    aiVerdict: null,
    auraStake: 150,
    viewers: 89,
  },
  {
    id: "b-6",
    sideA: "Minecraft",
    sideB: "Terraria",
    category: "Games",
    difficulty: "Bronze",
    difficultyColor: "text-red-400",
    teamA: [mockUsers[9], mockUsers[11], null, null, null],
    teamB: [mockUsers[10], mockUsers[8], null, null, null],
    spectators: [],
    maxSpectators: 50,
    status: "waiting",
    timer: 180,
    totalTimer: 180,
    chatMessages: [],
    aiVerdict: null,
    auraStake: 40,
    viewers: 15,
  },
  {
    id: "b-7",
    sideA: "Zelda",
    sideB: "Elden Ring",
    category: "Games",
    difficulty: "Platinum",
    difficultyColor: "text-amber-400",
    teamA: [mockUsers[0], mockUsers[2], mockUsers[4], mockUsers[7], mockUsers[10]],
    teamB: [mockUsers[1], mockUsers[3], mockUsers[5], mockUsers[8], mockUsers[11]],
    spectators: [mockUsers[6], mockUsers[9]],
    maxSpectators: 300,
    status: "finished",
    timer: 0,
    totalTimer: 600,
    chatMessages: [],
    aiVerdict: {
      winner: "B",
      scoreA: 81,
      scoreB: 88,
      bestArgument: {
        userId: "u-2",
        username: "AR",
        text: "Elden Ring redefined the open-world genre. Miyazaki's world-building combined with George R.R. Martin's lore created something unprecedented.",
      },
      mostRoasted: {
        userId: "u-10",
        username: "MR",
        roastCount: 3,
      },
      summary: "Team Elden Ring cooked Team Zelda like a low-level mob. The lore depth and combat complexity arguments hit harder than any Lynel ever could. Zelda's 'but it's accessible!' plea was the gaming equivalent of bringing a spoon to a sword fight.",
      coinsAwarded: 300,
      auraChange: { gained: 220, lost: 150 },
    },
    auraStake: 300,
    viewers: 175,
  },

  // --- Anime ---
  {
    id: "b-8",
    sideA: "Naruto",
    sideB: "Goku",
    category: "Anime",
    difficulty: "Platinum",
    difficultyColor: "text-amber-400",
    teamA: [mockUsers[0], mockUsers[3], mockUsers[5], mockUsers[8], mockUsers[11]],
    teamB: [mockUsers[1], mockUsers[4], mockUsers[6], mockUsers[9], mockUsers[10]],
    spectators: [mockUsers[2], mockUsers[7]],
    maxSpectators: 300,
    status: "live",
    timer: 98,
    totalTimer: 600,
    chatMessages: [
      {
        id: "cm-15",
        userId: "u-1",
        username: "DK",
        text: "Naruto went from village outcast to the man who saved the entire shinobi world. Goku went from strong to stronger to EVEN STRONGER. That's not character development, that's a powerpoint with animations.",
        timestamp: Date.now() - 200000,
        isAi: false,
        type: "argument",
      },
      {
        id: "cm-16",
        userId: "u-2",
        username: "AR",
        text: "Goku's influence spans DECADES and birthed entire genres. Naruto exists because Dragon Ball carved the path. You don't thank the student for the master's work.",
        timestamp: Date.now() - 180000,
        isAi: false,
        type: "argument",
      },
      {
        id: "cm-17",
        userId: "u-5",
        username: "RM",
        text: "Naruto's Pain Arc made people question their life choices at 3am. Goku's arcs make people go 'woo new form!' One is literature, the other is a gym playlist.",
        timestamp: Date.now() - 150000,
        isAi: false,
        type: "argument",
      },
      {
        id: "cm-18",
        userId: "ai",
        username: "AI Roastmaster",
        text: "[Roastmaster] @RK eliminated — low-effort argument. Provide specific examples or evidence.",
        timestamp: Date.now() - 120000,
        isAi: true,
        type: "ai_kick",
      },
      {
        id: "cm-19",
        userId: "u-7",
        username: "SP",
        text: "This debate has more heat than Kamehameha vs Rasengan 🔥🔥",
        timestamp: Date.now() - 80000,
        isAi: false,
        type: "spectator_reaction",
        reaction: "🔥",
      },
    ],
    aiVerdict: null,
    auraStake: 300,
    viewers: 200,
  },
  {
    id: "b-9",
    sideA: "One Piece",
    sideB: "Demon Slayer",
    category: "Anime",
    difficulty: "Gold",
    difficultyColor: "text-red-400",
    teamA: [mockUsers[2], mockUsers[6], mockUsers[10], null, null],
    teamB: [mockUsers[5], mockUsers[9], mockUsers[11], null, null],
    spectators: [mockUsers[0], mockUsers[1], mockUsers[4]],
    maxSpectators: 200,
    status: "waiting",
    timer: 240,
    totalTimer: 300,
    chatMessages: [],
    aiVerdict: null,
    auraStake: 150,
    viewers: 72,
  },
  {
    id: "b-10",
    sideA: "AOT",
    sideB: "JJK",
    category: "Anime",
    difficulty: "Silver",
    difficultyColor: "text-zinc-400",
    teamA: [mockUsers[4], mockUsers[7], mockUsers[8], null, null],
    teamB: [mockUsers[6], mockUsers[9], null, null, null],
    spectators: [mockUsers[3], mockUsers[10]],
    maxSpectators: 100,
    status: "finished",
    timer: 0,
    totalTimer: 240,
    chatMessages: [],
    aiVerdict: {
      winner: "A",
      scoreA: 85,
      scoreB: 71,
      bestArgument: {
        userId: "u-5",
        username: "RM",
        text: "Attack on Titan's plot twists are genuinely unpredictable. The basement reveal, the time skip, the ending — no anime has matched that level of narrative ambition.",
      },
      mostRoasted: {
        userId: "u-9",
        username: "BT",
        roastCount: 2,
      },
      summary: "Team AOT absolutely body-slammed JJK. JJK's 'but the animation!' argument is like praising a fireworks show for being pretty — AOT rewrote the rules of storytelling while JJK is still learning the alphabet of narrative.",
      coinsAwarded: 150,
      auraChange: { gained: 100, lost: 70 },
    },
    auraStake: 80,
    viewers: 43,
  },

  // --- Cartoons ---
  {
    id: "b-10a",
    sideA: "Rick & Morty",
    sideB: "BoJack Horseman",
    category: "Cartoons",
    difficulty: "Gold",
    difficultyColor: "text-red-400",
    teamA: [mockUsers[0], mockUsers[3], mockUsers[6], null, null],
    teamB: [mockUsers[2], mockUsers[5], mockUsers[9], null, null],
    spectators: [mockUsers[1], mockUsers[7], mockUsers[8]],
    maxSpectators: 200,
    status: "live",
    timer: 195,
    totalTimer: 300,
    chatMessages: [
      {
        id: "cm-40",
        userId: "u-1",
        username: "DK",
        text: "Rick & Morty makes you laugh AND question existence in the same episode. BoJack just makes you stare at a wall and reevaluate every friendship you've ever had.",
        timestamp: Date.now() - 150000,
        isAi: false,
        type: "argument",
      },
      {
        id: "cm-41",
        userId: "u-3",
        username: "PS",
        text: "Rick's whole 'I'm the smartest man in the universe' shtick is just arrogant nihilism with a laugh track. BoJack made depression watchable. That's actual genius.",
        timestamp: Date.now() - 120000,
        isAi: false,
        type: "argument",
      },
      {
        id: "cm-42",
        userId: "ai",
        username: "AI Roastmaster",
        text: "[Roastmaster] @MR warned — stay on topic. Personal insults toward other debaters will result in elimination.",
        timestamp: Date.now() - 90000,
        isAi: true,
        type: "ai_warning",
      },
      {
        id: "cm-43",
        userId: "u-4",
        username: "VK",
        text: "BoJack's 'Hollywoo' episode alone has more emotional intelligence than Rick & Morty's entire multiverse. One show uses sci-fi as a crutch, the other uses cartoons as a mirror.",
        timestamp: Date.now() - 60000,
        isAi: false,
        type: "argument",
      },
      {
        id: "cm-44",
        userId: "u-8",
        username: "AJ",
        text: "💀💀 This debate is deeper than half my college courses",
        timestamp: Date.now() - 30000,
        isAi: false,
        type: "spectator_reaction",
        reaction: "💀",
      },
    ],
    aiVerdict: null,
    auraStake: 150,
    viewers: 112,
  },
  {
    id: "b-10b",
    sideA: "SpongeBob",
    sideB: "Phineas & Ferb",
    category: "Cartoons",
    difficulty: "Silver",
    difficultyColor: "text-zinc-400",
    teamA: [mockUsers[8], mockUsers[10], mockUsers[11], null, null],
    teamB: [mockUsers[6], mockUsers[9], null, null, null],
    spectators: [mockUsers[0], mockUsers[4]],
    maxSpectators: 100,
    status: "waiting",
    timer: 180,
    totalTimer: 240,
    chatMessages: [],
    aiVerdict: null,
    auraStake: 80,
    viewers: 41,
  },

  // --- Sports ---
  {
    id: "b-11",
    sideA: "Messi",
    sideB: "Ronaldo",
    category: "Sports",
    difficulty: "Platinum",
    difficultyColor: "text-amber-400",
    teamA: [mockUsers[0], mockUsers[2], mockUsers[4], mockUsers[6], mockUsers[8]],
    teamB: [mockUsers[1], mockUsers[3], mockUsers[5], mockUsers[7], mockUsers[9]],
    spectators: [mockUsers[10], mockUsers[11]],
    maxSpectators: 500,
    status: "live",
    timer: 320,
    totalTimer: 600,
    chatMessages: [
      {
        id: "cm-20",
        userId: "u-1",
        username: "DK",
        text: "8 Ballon d'Ors. World Cup winner. The most trophies in football history. Numbers don't lie, but Ronaldo fans do.",
        timestamp: Date.now() - 250000,
        isAi: false,
        type: "argument",
      },
      {
        id: "cm-21",
        userId: "u-2",
        username: "AR",
        text: "Ronaldo proved himself in 4 different leagues and dominated them all. Messi stayed in Barcelona like a comfort blanket. Greatness requires leaving the nest.",
        timestamp: Date.now() - 220000,
        isAi: false,
        type: "argument",
      },
      {
        id: "cm-22",
        userId: "u-4",
        username: "VK",
        text: "Champions League top scorer ALL TIME. Ronaldo eats pressure for breakfast. In the biggest games, he shows up like he owes the stadium money.",
        timestamp: Date.now() - 180000,
        isAi: false,
        type: "argument",
      },
      {
        id: "cm-23",
        userId: "ai",
        username: "AI Roastmaster",
        text: "[Roastmaster] @MR eliminated — personal attacks are not arguments. Debate the topic, not the person.",
        timestamp: Date.now() - 140000,
        isAi: true,
        type: "ai_kick",
      },
      {
        id: "cm-24",
        userId: "u-3",
        username: "PS",
        text: "World Cup. The ONLY prize that matters on the international stage. Messi has it, Ronaldo has highlight reels of his World Cup campaigns. Case closed.",
        timestamp: Date.now() - 100000,
        isAi: false,
        type: "argument",
      },
      {
        id: "cm-25",
        userId: "u-8",
        username: "AJ",
        text: "This GOAT debate is going to end friendships and I'm HERE for it 😭😭🔥",
        timestamp: Date.now() - 60000,
        isAi: false,
        type: "spectator_reaction",
        reaction: "😭",
      },
    ],
    aiVerdict: null,
    auraStake: 400,
    viewers: 342,
  },
  {
    id: "b-12",
    sideA: "India",
    sideB: "Pakistan",
    category: "Sports",
    difficulty: "Gold",
    difficultyColor: "text-red-400",
    teamA: [mockUsers[0], mockUsers[3], mockUsers[7], null, null],
    teamB: [mockUsers[1], mockUsers[4], mockUsers[8], null, null],
    spectators: [mockUsers[2], mockUsers[5], mockUsers[9], mockUsers[10], mockUsers[11]],
    maxSpectators: 500,
    status: "finished",
    timer: 0,
    totalTimer: 300,
    chatMessages: [],
    aiVerdict: {
      winner: "A",
      scoreA: 78,
      scoreB: 72,
      bestArgument: {
        userId: "u-1",
        username: "DK",
        text: "India's ICC tournament record speaks for itself — 4 World Cups, 2 T20 World Cups, 3 Champions Trophies. Consistent dominance across formats.",
      },
      mostRoasted: {
        userId: "u-11",
        username: "HS",
        roastCount: 3,
      },
      summary: "Team India came in with a trophy cabinet that doubles as a war memorial for opponents. Pakistan fought hard with individual brilliance but ICC tournaments don't care about solo performances — they care about lifting the cup.",
      coinsAwarded: 200,
      auraChange: { gained: 140, lost: 95 },
    },
    auraStake: 200,
    viewers: 287,
  },
  {
    id: "b-13",
    sideA: "Federer",
    sideB: "Nadal",
    category: "Sports",
    difficulty: "Silver",
    difficultyColor: "text-zinc-400",
    teamA: [mockUsers[5], mockUsers[8], null, null, null],
    teamB: [mockUsers[6], mockUsers[9], null, null, null],
    spectators: [mockUsers[0]],
    maxSpectators: 100,
    status: "waiting",
    timer: 180,
    totalTimer: 240,
    chatMessages: [],
    aiVerdict: null,
    auraStake: 80,
    viewers: 28,
  },

  // --- Food ---
  {
    id: "b-14",
    sideA: "Biryani",
    sideB: "Pizza",
    category: "Food",
    difficulty: "Bronze",
    difficultyColor: "text-red-400",
    teamA: [mockUsers[7], mockUsers[10], null, null, null],
    teamB: [mockUsers[8], mockUsers[11], null, null, null],
    spectators: [],
    maxSpectators: 50,
    status: "waiting",
    timer: 120,
    totalTimer: 180,
    chatMessages: [],
    aiVerdict: null,
    auraStake: 40,
    viewers: 22,
  },
  {
    id: "b-15",
    sideA: "North Indian",
    sideB: "South Indian",
    category: "Food",
    difficulty: "Silver",
    difficultyColor: "text-zinc-400",
    teamA: [mockUsers[4], mockUsers[9], mockUsers[11], null, null],
    teamB: [mockUsers[5], mockUsers[10], null, null, null],
    spectators: [mockUsers[3]],
    maxSpectators: 100,
    status: "finished",
    timer: 0,
    totalTimer: 240,
    chatMessages: [],
    aiVerdict: {
      winner: "B",
      scoreA: 73,
      scoreB: 80,
      bestArgument: {
        userId: "u-6",
        username: "NK",
        text: "South Indian cuisine is recognized by UNESCO. Dosa, idli, sambar — it's not just food, it's heritage with incredible nutritional balance.",
      },
      mostRoasted: {
        userId: "u-12",
        username: "RK",
        roastCount: 1,
      },
      summary: "Team South Indian served a masterclass in nutrition, heritage, and variety. Team North Indian's 'but it's rich and creamy' defense crumbled faster than a butter naan. Turns out, you can't beat UNESCO with ghee alone.",
      coinsAwarded: 120,
      auraChange: { gained: 85, lost: 55 },
    },
    auraStake: 80,
    viewers: 56,
  },

  // --- Music ---
  {
    id: "b-16",
    sideA: "Arijit",
    sideB: "Atif",
    category: "Music",
    difficulty: "Gold",
    difficultyColor: "text-red-400",
    teamA: [mockUsers[2], mockUsers[6], mockUsers[9], null, null],
    teamB: [mockUsers[3], mockUsers[7], mockUsers[10], null, null],
    spectators: [mockUsers[0], mockUsers[1], mockUsers[4]],
    maxSpectators: 200,
    status: "live",
    timer: 170,
    totalTimer: 300,
    chatMessages: [
      {
        id: "cm-26",
        userId: "u-3",
        username: "PS",
        text: "Arijit Singh has the most streamed songs on Spotify India. The man IS modern Indian music — every breakup playlist bows to him.",
        timestamp: Date.now() - 130000,
        isAi: false,
        type: "argument",
      },
      {
        id: "cm-27",
        userId: "u-4",
        username: "VK",
        text: "Atif Aslam crossed borders that governments couldn't. His India concerts sell out in minutes. You don't need Spotify stats when you have nations fighting over you.",
        timestamp: Date.now() - 110000,
        isAi: false,
        type: "argument",
      },
      {
        id: "cm-28",
        userId: "u-9",
        username: "BT",
        text: "Both are legends but this debate is spicier than the songs themselves 🎵🔥",
        timestamp: Date.now() - 80000,
        isAi: false,
        type: "spectator_reaction",
        reaction: "🎵",
      },
    ],
    aiVerdict: null,
    auraStake: 150,
    viewers: 94,
  },
  {
    id: "b-17",
    sideA: "Rap",
    sideB: "Lo-fi",
    category: "Music",
    difficulty: "Silver",
    difficultyColor: "text-zinc-400",
    teamA: [mockUsers[8], mockUsers[11], null, null, null],
    teamB: [mockUsers[9], mockUsers[10], null, null, null],
    spectators: [mockUsers[5]],
    maxSpectators: 100,
    status: "waiting",
    timer: 180,
    totalTimer: 240,
    chatMessages: [],
    aiVerdict: null,
    auraStake: 80,
    viewers: 31,
  },

  // --- Tech ---
  {
    id: "b-18",
    sideA: "Apple",
    sideB: "Android",
    category: "Tech",
    difficulty: "Gold",
    difficultyColor: "text-red-400",
    teamA: [mockUsers[1], mockUsers[4], mockUsers[8], null, null],
    teamB: [mockUsers[2], mockUsers[5], mockUsers[9], null, null],
    spectators: [mockUsers[0], mockUsers[3], mockUsers[6], mockUsers[7]],
    maxSpectators: 200,
    status: "finished",
    timer: 0,
    totalTimer: 300,
    chatMessages: [],
    aiVerdict: {
      winner: "B",
      scoreA: 76,
      scoreB: 83,
      bestArgument: {
        userId: "u-3",
        username: "PS",
        text: "Android powers 72% of global smartphones. Open source, customizable, and accessible across all price points. It's democracy in tech.",
      },
      mostRoasted: {
        userId: "u-10",
        username: "MR",
        roastCount: 2,
      },
      summary: "Team Android demolished Team Apple's walled garden. Apple's 'but privacy!' defense folded the moment someone pointed out that Android powers the phones of 7 billion people. Premium pricing isn't an argument — it's a flex that most of the world can't afford.",
      coinsAwarded: 180,
      auraChange: { gained: 130, lost: 90 },
    },
    auraStake: 150,
    viewers: 145,
  },
  {
    id: "b-19",
    sideA: "PC",
    sideB: "Console",
    category: "Tech",
    difficulty: "Silver",
    difficultyColor: "text-zinc-400",
    teamA: [mockUsers[3], mockUsers[7], mockUsers[11], null, null],
    teamB: [mockUsers[4], mockUsers[8], null, null, null],
    spectators: [mockUsers[1], mockUsers[2]],
    maxSpectators: 100,
    status: "live",
    timer: 88,
    totalTimer: 240,
    chatMessages: [
      {
        id: "cm-29",
        userId: "u-4",
        username: "VK",
        text: "PC gaming has mods, better graphics, and Steam sales that save you more money than a console's entire existence. You're not 'choosing simplicity' — you're choosing to be poor in pixel quality.",
        timestamp: Date.now() - 100000,
        isAi: false,
        type: "argument",
      },
      {
        id: "cm-30",
        userId: "u-5",
        username: "RM",
        text: "Consoles deliver consistent performance without you needing a degree in GPU thermals. Plug, play, and actually enjoy the game instead of troubleshooting driver updates.",
        timestamp: Date.now() - 75000,
        isAi: false,
        type: "argument",
      },
      {
        id: "cm-31",
        userId: "ai",
        username: "AI Roastmaster",
        text: "[Roastmaster] @HS warned — personal attack on other debater. Keep it professional.",
        timestamp: Date.now() - 50000,
        isAi: true,
        type: "ai_warning",
      },
    ],
    aiVerdict: null,
    auraStake: 80,
    viewers: 67,
  },

  // --- Viral ---
  {
    id: "b-20",
    sideA: "Flat Earth",
    sideB: "Round Earth",
    category: "Viral",
    difficulty: "Bronze",
    difficultyColor: "text-red-400",
    teamA: [mockUsers[10], mockUsers[11], null, null, null],
    teamB: [mockUsers[7], mockUsers[8], mockUsers[9], null, null],
    spectators: [mockUsers[0], mockUsers[1], mockUsers[2], mockUsers[3], mockUsers[4], mockUsers[5]],
    maxSpectators: 100,
    status: "live",
    timer: 55,
    totalTimer: 180,
    chatMessages: [
      {
        id: "cm-32",
        userId: "u-8",
        username: "AJ",
        text: "There are literally satellite photos from SPACE. The Earth is round. This debate is a comedy special and I'm the audience.",
        timestamp: Date.now() - 60000,
        isAi: false,
        type: "argument",
      },
      {
        id: "cm-33",
        userId: "u-10",
        username: "MR",
        text: "Water always finds its level. If Earth were spinning at 1000mph, we'd all be flung into oblivion. Open your eyes sheeple.",
        timestamp: Date.now() - 45000,
        isAi: false,
        type: "argument",
      },
      {
        id: "cm-34",
        userId: "u-1",
        username: "DK",
        text: "💀💀💀 I came to watch a roast and got a science fiction convention",
        timestamp: Date.now() - 30000,
        isAi: false,
        type: "spectator_reaction",
        reaction: "💀",
      },
      {
        id: "cm-35",
        userId: "u-2",
        username: "AR",
        text: "😂😂😂 This is the greatest entertainment on the internet right now",
        timestamp: Date.now() - 15000,
        isAi: false,
        type: "spectator_reaction",
        reaction: "😂",
      },
    ],
    aiVerdict: null,
    auraStake: 40,
    viewers: 156,
  },
  {
    id: "b-21",
    sideA: "Aliens Real",
    sideB: "Aliens Not Real",
    category: "Viral",
    difficulty: "Silver",
    difficultyColor: "text-zinc-400",
    teamA: [mockUsers[5], mockUsers[8], mockUsers[11], null, null],
    teamB: [mockUsers[6], mockUsers[9], mockUsers[10], null, null],
    spectators: [mockUsers[0], mockUsers[2], mockUsers[4]],
    maxSpectators: 100,
    status: "waiting",
    timer: 240,
    totalTimer: 240,
    chatMessages: [],
    aiVerdict: null,
    auraStake: 80,
    viewers: 48,
  },
];

// ============================================================
// Mock Quests
// ============================================================

export const mockQuests: Quest[] = [
  {
    id: "q-1",
    title: "Win 2 Roast Battles",
    description: "Drop 2 opponents with savage arguments and claim your aura.",
    progress: 1,
    target: 2,
    reward: { coins: 100, aura: 50 },
    completed: false,
    claimed: false,
  },
  {
    id: "q-2",
    title: "Roast Across 3 Categories",
    description: "Prove you're not a one-trick pony — roast in 3 different categories.",
    progress: 2,
    target: 3,
    reward: { coins: 150, aura: 75 },
    completed: false,
    claimed: false,
  },
  {
    id: "q-3",
    title: "Clean Roaster",
    description: "Complete a full battle without a single AI warning. Pure skill, no filters.",
    progress: 1,
    target: 1,
    reward: { coins: 200, aura: 100 },
    completed: true,
    claimed: true,
  },
  {
    id: "q-4",
    title: "Roast Connoisseur",
    description: "Watch 5 battles and study the GOATs of roasting. Take notes.",
    progress: 3,
    target: 5,
    reward: { coins: 75, aura: 25 },
    completed: false,
    claimed: false,
  },
];

// ============================================================
// Mock Marketplace Items
// ============================================================

export const mockMarketplaceItems: MarketplaceItem[] = [
  {
    id: "mp-1",
    name: "Fire Frame",
    type: "frame",
    cost: 500,
    rarity: "rare",
    rarityColor: "text-amber-400",
    owned: true,
    equipped: false,
    previewType: "border",
    description: "For arguments so hot they leave scars. Your opponents will feel the burn before you even type.",
  },
  {
    id: "mp-2",
    name: "Olive Crown",
    type: "frame",
    cost: 1200,
    rarity: "epic",
    rarityColor: "text-amber-400",
    owned: false,
    equipped: false,
    previewType: "border",
    description: "Wear this when your roasts are so clean, they're practically legal.",
  },
  {
    id: "mp-3",
    name: "The Roast King",
    type: "title",
    cost: 800,
    rarity: "rare",
    rarityColor: "text-amber-400",
    owned: true,
    equipped: true,
    previewType: "text",
    description: "The sharpest tongue in the arena. Your words don't just win arguments — they end careers.",
  },
  {
    id: "mp-4",
    name: "Supreme Judge",
    type: "title",
    cost: 2000,
    rarity: "legendary",
    rarityColor: "text-red-500",
    owned: false,
    equipped: false,
    previewType: "text",
    description: "When you drop a roast so devastating, even the AI Judge takes notes.",
  },
  {
    id: "mp-5",
    name: "Case Closer",
    type: "title",
    cost: 400,
    rarity: "common",
    rarityColor: "text-zinc-500",
    owned: true,
    equipped: false,
    previewType: "text",
    description: "That one roast that makes the other team go silent. Mic drop energy.",
  },
  {
    id: "mp-6",
    name: "Flame Streak",
    type: "badge",
    cost: 600,
    rarity: "rare",
    rarityColor: "text-amber-400",
    owned: false,
    equipped: false,
    previewType: "icon",
    description: "3 wins in a row? More like 3 opponents left in therapy.",
  },
  {
    id: "mp-7",
    name: "Crowd Legend",
    type: "badge",
    cost: 1500,
    rarity: "epic",
    rarityColor: "text-amber-400",
    owned: false,
    equipped: false,
    previewType: "icon",
    description: "The spectators don't just watch you — they worship you. Most reactions in a single battle.",
  },
  {
    id: "mp-8",
    name: "Aura Glow",
    type: "effect",
    cost: 3000,
    rarity: "legendary",
    rarityColor: "text-red-500",
    owned: false,
    equipped: false,
    previewType: "description",
    description: "A burning orange aura that says 'I'm here to roast and I'm not leaving until someone cries.'",
  },
];

// ============================================================
// Mock Groups
// ============================================================

export const mockGroups: GroupInfo[] = [
  {
    id: "g-1",
    name: "Movie Maniacs",
    members: 342,
    description: "The ultimate roast arena for cinema. From Bollywood to Hollywood — if it's on screen, it's getting roasted.",
    category: "Movies",
    isJoined: true,
  },
  {
    id: "g-2",
    name: "Anime Army",
    members: 521,
    description: "Shonen supremacy debates, waifu wars, and 'my anime is better than yours' roasts. No survivors.",
    category: "Anime",
    isJoined: true,
  },
  {
    id: "g-7",
    name: "Toon Squad",
    members: 198,
    description: "Cartoon roasts only. Rick & Morty vs BoJack, SpongeBob vs Phineas & Ferb. Saturday morning trauma, debated.",
    category: "Cartoons",
    isJoined: false,
  },
  {
    id: "g-3",
    name: "Game Lords",
    members: 289,
    description: "PC vs Console, Nintendo vs Sony. If you can't defend your game, don't bring it here.",
    category: "Games",
    isJoined: true,
  },
  {
    id: "g-4",
    name: "Food Fighters",
    members: 178,
    description: "Biryani vs Pizza, Chai vs Coffee. The food debates that divide nations and end friendships.",
    category: "Food",
    isJoined: false,
  },
  {
    id: "g-5",
    name: "Sports Squad",
    members: 415,
    description: "GOAT debates that get personal. Messi vs Ronaldo, India vs Pakistan — no mercy.",
    category: "Sports",
    isJoined: false,
  },
  {
    id: "g-6",
    name: "Tech Titans",
    members: 256,
    description: "Apple vs Android, AI vs Humans. Roast the tech you love and the tech you hate.",
    category: "Tech",
    isJoined: false,
  },
];